[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.MATC1ADivorceJointPetition"
version = "2.0.1"
description = "A docassemble interview to prepare and file papers to initiate a joint 1A divorce petition in Massachusetts."
readme = "README.md"
authors = [
    { name = "KP Hunsinger", email = "litlab@suffolk.edu" },
]
dependencies = [
    "docassemble.ALAffidavitOfIndigency>=2.3.0",
    "docassemble.MATCMotionToAmend @ git+https://github.com/SuffolkLITLab/docassemble-MATCMotionToAmend.git@f92797e3c417f142faec40fbce35d25fb8bf50d6",
    "docassemble.MATCFinancialStatement @ git+https://github.com/SuffolkLITLab/docassemble-MATCFinancialStatement.git@a1dbe3d228c7f36674217103abb082ae35610741",
    "docassemble.MATCSeparationAgreement @ git+https://github.com/SuffolkLITLab/docassemble-MATCSeparationAgreement.git@dce8a19a3249a7be750ddc326913bc2bb93c6dfe",
    "docassemble.MATCChildCareOrCustodyDisclosureAffidavit @ git+https://github.com/SuffolkLITLab/docassemble-MATCChildCareOrCustodyDisclosureAffidavit.git@08f31c860457e41ea757d3b1f8469c74a7a53556",
    "docassemble.MATCCSGWorksheet @ git+https://github.com/SuffolkLITLab/docassemble-MATCCSGWorksheet.git@96589474face58e0bbb18a067f4710e8e50e3d5a",
    "docassemble.matcfindingsanddeterminations @ git+https://github.com/SuffolkLITLab/docassemble-MATCFindingsAndDeterminations.git@9ce10b5f65b0fdd83919d151dee6d9a717723b26",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://docassemble.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
